# Generated by Django 4.2.5 on 2023-09-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="table.category",
            ),
        ),
    ]
